config/routes.rb
AssetTrackerTutorial::Application.routes.draw do
  root :to => "dashboard/base#index"

  devise_for :users, :path => '/', :path_names => { :sign_in => 'login', :sign_out => 'logout' }

  post "/data_vaults/:id", :to => "data_vaults#update"
  resources :data_vaults, :only => [:show]

  namespace :admin do
    resources :invoices
    resources :payroll
    get :locked_users, :controller => :users, :action => :locked_users
    resources :users do
      member do
        get :projects
        post :projects
      end
    end
    resources :projects
    resources :unentered_time_report
    resources :weekly_time_report
    resource :site_settings
  end
  get '/admin', :controller => "admin/base", :action => "index"
  get '/admin/reports', :controller => "admin/base", :action => "reports"

  namespace :client_login do
    root :to => "clients#index"
    resources :reports, :only => [:index] do
      collection do
        match :work_units
      end
    end
    resources :clients do
      resources :contacts
    end
    resources :projects, :tickets, :work_units
  end

  match '/client/:id' => 'clients#show'
  get :inactive_clients, :controller => :clients, :action => :inactive_clients
  get :suspended_clients, :controller => :clients, :action => :suspended_clients
  resources :clients do
    resources :comments
    resources :contacts
    get :show_complete, :controller => :clients, :action => :show_complete
  end

  resources :projects, :except => [:index, :destroy] do
    resources :comments
    get "show_complete", :controller => :projects, :action => "show_complete"
  end

  resources :tickets, :except => [:index, :destroy] do
    post 'advance_state', :controller => :tickets, :action => :advance_state
    post 'reverse_state', :controller => :tickets, :action => :reverse_state
    get 'ticket_detail', :controller => :tickets, :action => :ticket_detail
    put 'toggle_complete', :controller => :tickets, :action => :toggle_complete
    resources :comments
    resources :work_units
  end

  resources :work_units, :except => [:destroy, :create] do
    collection do 
      post :create_in_ticket
      post :create_in_dashboard
    end

    resources :comments
  end

  resources :users do
    member do
      put :change_password
      get :historical_time
    end
  end

  resources :comments

  resources :file_attachments

  namespace :dashboard do
    get :json_index, :controller => "base", :action => :json_index
    resources :base do
    end
  end

  get '/dashboard', :controller => "dashboard/base", :action => :index
  get '/dashboard/calendar', :controller => "dashboard/base", :action => "calendar"
  get '/dashboard/client', :controller => "dashboard/base", :action => "client"
  get '/dashboard/project', :controller => "dashboard/base", :action => "project"
  get '/dashboard/recent_work', :controller => "dashboard/base", :action => "recent_work"
  get '/dashboard/update_calendar', :controller => "dashboard/base", :action => "update_calendar"
  post '/file_attachments/mark_as_invalid', :controller => "file_attachments", :action => "mark_as_invalid"

  namespace :api do
    namespace :v1 do
      resources :tokens, :only => [:create, :destroy]
      resources :clients, :only => [:index]
      resources :projects, :only => [:index, :create]
      resources :tickets, :only => [:index, :show, :create]
      resources :work_units, :only => [:index, :create]
    end
  end
end

app/controllers/admin/base_controller.rb
class Admin::BaseController < ApplicationController
  before_filter :require_admin
  helper :admin_base

  def index
  end

  def reports
  end
end

app/controllers/api/base_controller.rb
class Api::BaseController < ApplicationController
  skip_before_filter :authenticate_user!
  skip_before_filter :verify_authenticity_token
  before_filter :verify_api_login
  respond_to :json

  def verify_api_login
    render :json => {:success => false} unless current_user && params[:auth_token]
  end
end

app/controllers/api/v1/base_controller.rb
class Api::V1::BaseController < Api::BaseController
end

app/controllers/client_login/base_controller.rb
class ClientLogin::BaseController < ApplicationController
  skip_before_filter :redirect_clients
end

app/controllers/dashboard/base_controller.rb
class Dashboard::BaseController < ApplicationController
  include ActionView::Helpers::SanitizeHelper
  before_filter :get_calendar_details, :only => [:index, :calendar, :update_calendar]
  before_filter :load_work_units, :only => [:index, :calendar, :update_calendar]
  respond_to :html, :json, :js

  def json_index
    bucket = decide_bucket
    bucket = bucket.for_user(current_user) unless params["all"] == "true"
    bucket.order("name")
    render :json => bucket.all
  end

  def index
    @message = {:title => t(:management), :body => t(:enter_time_for_previous_day)} unless current_user.entered_time_yesterday?
    @clients = Client.order("name").active.for_user(current_user)
    @projects = []
    @tickets = []

    @project_report_rows = WorkUnit.for_user(current_user).scheduled_between(Time.zone.now - 2.weeks, Time.zone.now.end_of_day).joins(:ticket => :project).select("projects.name as project_name, projects.id as project_id, SUM(work_units.effective_hours) as total_hours").group("projects.name, projects.id").sort_by{|r| r.total_hours}.reverse # Sort in ruby because I ran into sql problems - should be sorting like 5 rows max so no worries
  end

  def client
    @projects = Project.order("name").incomplete.for_client_id(params[:id])
    unless admin?
      @projects = @projects.for_user_and_role(current_user, :developer)
    end
    respond_with @projects
  end

  def project
    @tickets = Ticket.order("name").incomplete.where("project_id = ?", params[:id])
    #unless admin?
    #  @tickets = @tickets.for_user_and_role(current_user, :developer)
    #end
    respond_with @tickets
  end

  def calendar
  end

  def load_work_units
    @work_units = current_user.work_units_between(@start_date, @start_date + 6.days)
  end

  def update_calendar
    respond_to do |format|
      format.js {
        render :json => {
          :success => true,
          :data => render_to_string(
            :partial => 'shared/calendar',
            :locals => {
              :start_date => @start_date,
              :work_units => @work_units,
              :user => current_user
            }
          ),
          :week_pagination => render_to_string(
            :partial => 'dashboard/base/week_pagination',
            :locals => {
              :start_date => @start_date
            }
          )
        }
      }
    end
  end

  private

  def decide_bucket
    case params["bucket"]
    when "Client"
      Client.active
    when "Project"
      Project.incomplete.where("client_id = ?", params[:id])
    when "Ticket"
      Ticket.incomplete.where("project_id = ?", params[:id])
    end
  end
end

app/helpers/dashboard_helper.rb
module DashboardHelper
  def render_message(message)
    if message
      content_tag('div', :id => 'message', :title => message[:title], :style => 'display: none;') do
        content_tag('p', message[:body])
      end
    end
  end
end

app/views/dashboard/base/_two_week_time_report.html.haml
- if @project_report_rows.any?
  %table.table.table-striped.table-bordered
    %thead
      %th{:colspan => 2}
        = "Project time report from #{(Time.zone.now - 2.weeks).to_date} to #{Time.zone.now.end_of_day.to_date}"
    %tbody
      %tr
        %th Project
        %th Hours
      - @project_report_rows.each do |project_report|
        %tr
          %td= link_to(project_report.project_name, project_path(project_report.project_id))
          %td= project_report.total_hours

app/views/dashboard/base/_week_pagination.html.haml
.date_pagination
  .row-fluid
    .span.first
      = link_to t(:previous_week).html_safe, dashboard_path(:date => (@start_date - 1.week).strftime("%F")), :class => "previous_week recent_work get_week_calendar previous"
    .span
      - unless (start_date..(start_date + 6.days)).include?(Date.current)
        = link_to t(:current), dashboard_path, :class => "today recent_work get_week_calendar"
    .span.last
      -# if (start_date + 6.days) < Date.current     <---- prevents viewing future dates on dashboard calendar
      = link_to t(:next_week).html_safe, dashboard_path(:date => (@start_date + 1.week)), :class => "next_week recent_work get_week_calendar"

app/views/dashboard/base/calendar.html.haml
= render 'shared/calendar', :start_date => @start_date, :user => current_user, :work_units => @work_units

app/views/dashboard/base/calendar.js.erb
<%- calendar_output = render('shared/calendar', :start_date => @start_date, :user => current_user, :work_units => @work_units) -%>
$('.calendar').html('<%= escape_javascript(calendar_output) -%>');
$('.calendar table tbody').effect('highlight');

app/views/dashboard/base/index.html.haml
.week_pagination
  = render 'dashboard/base/week_pagination', :start_date => @start_date

= render 'shared/calendar', :start_date => @start_date, :user => current_user, :work_units => @work_units

.row-fluid
  .span6
    = render 'tickets/add_ticket'
  .span6
    = render 'work_units/add_work_unit'

.dashboard_2week_time_report
  = render 'two_week_time_report'

= render_message(@message)

- content_for :javascripts do
  = javascript_include_tag 'add_taxonomy'