config/routes.rb
AssetTrackerTutorial::Application.routes.draw do
  root :to => "dashboard/base#index"

  devise_for :users, :path => '/', :path_names => { :sign_in => 'login', :sign_out => 'logout' }

  post "/data_vaults/:id", :to => "data_vaults#update"
  resources :data_vaults, :only => [:show]

  namespace :admin do
    resources :invoices
    resources :payroll
    get :locked_users, :controller => :users, :action => :locked_users
    resources :users do
      member do
        get :projects
        post :projects
      end
    end
    resources :projects
    resources :unentered_time_report
    resources :weekly_time_report
    resource :site_settings
  end
  get '/admin', :controller => "admin/base", :action => "index"
  get '/admin/reports', :controller => "admin/base", :action => "reports"

  namespace :client_login do
    root :to => "clients#index"
    resources :reports, :only => [:index] do
      collection do
        match :work_units
      end
    end
    resources :clients do
      resources :contacts
    end
    resources :projects, :tickets, :work_units
  end

  match '/client/:id' => 'clients#show'
  get :inactive_clients, :controller => :clients, :action => :inactive_clients
  get :suspended_clients, :controller => :clients, :action => :suspended_clients
  resources :clients do
    resources :comments
    resources :contacts
    get :show_complete, :controller => :clients, :action => :show_complete
  end

  resources :projects, :except => [:index, :destroy] do
    resources :comments
    get "show_complete", :controller => :projects, :action => "show_complete"
  end

  resources :tickets, :except => [:index, :destroy] do
    post 'advance_state', :controller => :tickets, :action => :advance_state
    post 'reverse_state', :controller => :tickets, :action => :reverse_state
    get 'ticket_detail', :controller => :tickets, :action => :ticket_detail
    put 'toggle_complete', :controller => :tickets, :action => :toggle_complete
    resources :comments
    resources :work_units
  end

  resources :work_units, :except => [:destroy, :create] do
    collection do 
      post :create_in_ticket
      post :create_in_dashboard
    end

    resources :comments
  end

  resources :users do
    member do
      put :change_password
      get :historical_time
    end
  end

  resources :comments

  resources :file_attachments

  namespace :dashboard do
    get :json_index, :controller => "base", :action => :json_index
    resources :base do
    end
  end

  get '/dashboard', :controller => "dashboard/base", :action => :index
  get '/dashboard/calendar', :controller => "dashboard/base", :action => "calendar"
  get '/dashboard/client', :controller => "dashboard/base", :action => "client"
  get '/dashboard/project', :controller => "dashboard/base", :action => "project"
  get '/dashboard/recent_work', :controller => "dashboard/base", :action => "recent_work"
  get '/dashboard/update_calendar', :controller => "dashboard/base", :action => "update_calendar"
  post '/file_attachments/mark_as_invalid', :controller => "file_attachments", :action => "mark_as_invalid"

  namespace :api do
    namespace :v1 do
      resources :tokens, :only => [:create, :destroy]
      resources :clients, :only => [:index]
      resources :projects, :only => [:index, :create]
      resources :tickets, :only => [:index, :show, :create]
      resources :work_units, :only => [:index, :create]
    end
  end
end

app/views/shared/_calendar.html.haml
.calendar
  %table.table.table-striped
    %thead
      %tr.calendar_top
        - (0..6).map{|x| start_date + x.days }.each do |date|
          %th= "#{date.asctime[0]} - #{date.day}"
        %th
          = link_to '[+/-]', '#', :class => 'expand'
          = "#{t(:totals)}:"
    %tfoot
      %tr.calendar_foot
        - (0..6).map{|x| start_date + x.days }.each do |date|
          %td.span2= "#{t(:total)}: #{work_units.select{|wu| wu.scheduled_at.to_date == date.to_date}.inject(BigDecimal("0")){|sum,x| sum + x.effective_hours}}"
        %td.span2{ :colspan => 2 }= "#{t(:week)}: #{work_units.inject(BigDecimal("0")){|sum,x| sum + x.effective_hours}}"
    %tbody
      %tr
        - (start_date..(start_date + 6.days)).each do |date|
          %td.span2
            - unless work_units.select{|wu| wu.scheduled_at.to_date == date.to_date}.empty?
              %ul.unstyled
                - work_units.select{|wu| wu.scheduled_at.to_date == date.to_date}.each do |work_unit|
                  %li{:class => "work_unit " << work_unit.hours_type.downcase }
                    - render_label_for(work_unit.hours_type)
                    = link_to "#{work_unit.client.initials}: #{work_unit.effective_hours}", work_unit_path(work_unit), { :title => work_unit.description, :rel => 'tooltip' }
                    %span.description= '- ' + work_unit.description

        %td.span2
          %ul.unstyled
            - if start_date == Date.current.beginning_of_week
              %li#current_hours= "#{t(:current)}: #{user.unpaid_work_units.sum(:effective_hours)}"
            - if @site_settings.total_yearly_pto_per_user
              %li#pto_left= "#{t(:pto_left)}: #{user.pto_hours_left(start_date.end_of_week)}"
            - if user.daily_target_hours
              %li#target_hours= "#{t(:target_hours_offset)}: #{user.target_hours_offset(last_effective_date(start_date))}"
            - if @site_settings.client && work_units.present?
              %li#external_percentage= "#{t(:external_percentage)}: #{external_work_percentage(user, start_date.beginning_of_week, start_date.end_of_week)}%"
        %td.span2{:id => "#{user.id}_chart"}
- if request.xhr?
  :javascript
    $('a[rel=twipsy]').tooltip({ placement: 'bottom'} );
    // Create the data table.
    var data = new google.visualization.DataTable();
    data.addColumn('string', 'Day');
    data.addColumn('number', 'External Hours');
    data.addColumn('number', 'Internal Hours');
    data.addRows(#{external_hours_for_chart(user, :date => start_date)});

        // Set chart options
    var options = {'title':'Weekly Hours',
      'width':250,
      'backgroundColor': "#f5f5f5",
      'isStacked': true,
      'legend': {position: 'none'},
      'height':120};

    // Instantiate and draw our chart, passing in some options.
    var chart = new google.visualization.ColumnChart(document.getElementById("#{user.id}_chart"));
    chart.draw(data, options);
- else
  - content_for :javascripts do
    :javascript
      $('a[rel=twipsy]').tooltip({ placement: 'bottom'} );

      google.load('visualization', '1.0', {'packages':['corechart']});
      google.setOnLoadCallback(drawChart);

      function drawChart() {
        // Create the data table.
          var data = new google.visualization.DataTable();
          data.addColumn('string', 'Day');
          data.addColumn('number', 'External Hours');
          data.addColumn('number', 'Internal Hours');
          data.addRows(#{external_hours_for_chart(user, :date => start_date)});

              // Set chart options
          var options = {'title':'Weekly Hours',
            'width':250,
            'backgroundColor': "#f5f5f5",
            'isStacked': true,
            'legend': {position: 'none'},
            'height':120};

          // Instantiate and draw our chart, passing in some options.
          var chart = new google.visualization.ColumnChart(document.getElementById("#{user.id}_chart"));
          chart.draw(data, options);
      }

app/views/shared/_data_vault.html.haml
-if data_vault
  .autogrow
    :kramdown
      #{data_vault.data}

-content_for :javascripts do 
  :javascript
    $('.autogrow').editable('/data_vaults/#{data_vault.id}', {
      type:    "textarea",
      tooltip: "Double Click to edit",
      loadurl: "#{data_vault_path(data_vault)}",
      cancel: "Cancel",
      onblur: "submit",
      rows: 25,
      event: "dblclick"
    });

app/views/shared/_files_and_comments.html.haml
#files_and_comments
  %h3= "#{t(:files_and_comments)}:"
  = link_to "Hide/Show hidden", "#comments", :id => 'hide_show_comments'
  %p
  %hr  
  - items.each do |item|
    - if item.is_a? Comment
      = render 'comments/comment', :comment => item
    - elsif item.is_a? FileAttachment
      = render 'file_attachments/file_attachment_combined', :file_attachment => item
    %hr  
  %p
  - if id == 'client'
    = render "comments/comment_form",  :commentable_id => @client.id, :commentable_field => "client_id", :commentable_type => "Client", :refurl => client_path(@client), :comment_num => @client.id
    = link_to t(:add_file_attachment), new_file_attachment_path( :client_id => @client.id )
  - elsif id == 'project'
    = render "comments/comment_form", :commentable_id => @project.id, :commentable_field => "project_id", :commentable_type => "Project", :refurl => project_path(@project), :comment_num => @project.id
    = link_to t(:add_file_attachment), new_file_attachment_path( :project_id => @project.id )
  - elsif id == 'ticket'
    = render "comments/comment_form", :commentable_id => @ticket.id, :commentable_field => "ticket_id", :commentable_type => "Ticket", :refurl => ticket_path(@ticket), :comment_num => @ticket.id
    = link_to t(:add_file_attachment), new_file_attachment_path( :ticket_id => @ticket.id )

app/views/shared/_flashes.html.haml
- flash.each do |key, message|
  %div{ :class => "alert, alert-message fade in #{key}", "data-alert" => "data-alert" }
    %p= message
- content_for :javascripts do
  :javascript
    $(document).ready(function() {
      $('.notice').delay(3000).slideUp(300)
      $('.error').delay(3000).slideUp(300)
      $('.warning').delay(3000).slideUp(300)
    });

app/views/shared/_javascripts.html.haml
- if current_user.try(:expanded_calendar)
  :javascript
    calendar_expansion_default = true; 
= javascript_include_tag 'application'
= javascript_include_tag "https://www.google.com/jsapi"
= yield :javascripts
:javascript
  $('.dropdown-toggle').dropdown()

app/views/shared/_menu.html.haml
- if !current_user or !current_user.client
  = render_navigation(:level => :all, :expand_all => true, :renderer => :bootstrap)
- elsif current_user and current_user.client
  = render_navigation(:level => 1, :context => 'client')

- if current_user
  %ul.nav.pull-right
    %li.dropdown
      %a{:href => '#', :class => 'dropdown-toggle', 'data-toggle' => 'dropdown'}
        = show_gravatar_for(current_user, 30)
        %span
          = current_user
        %b.caret
      = render_navigation(:level => 1, :context => 'secondary')

app/views/shared/_user_roles.html.haml
- Project.for_client(client).sort_by_name.each do |project|
  %tr{ :class => "#{cycle("odd", "even")} #{client.status.downcase}"  }
    %td= client
    %td= project
    %td= radio_button_tag("project[#{project.id}]", "developer", user.has_role?(:developer, project))
    %td= radio_button_tag("project[#{project.id}]", "client", user.has_role?(:client, project))
    %td= radio_button_tag("project[#{project.id}]", "no_access", user.roles_for(project).empty?)

app/views/shared/_work_unit_index.haml
%table.work_units.table.table-striped
  %thead
    %tr
      %th #
      %th= t(:work_units)
      %th= t(:creator)
      %th= t(:scheduled_at)
      %th= t(:hours_type)
      %th= t(:hours)            
  %tbody
    - @work_units.each do |work_unit|
      %tr{ :class => cycle("odd", "even") }
        %td= work_unit.id
        %td= link_to work_unit.description, work_unit_path(work_unit)
        %td= work_unit.user.first_name
        %td= work_unit.scheduled_at
        %td= work_unit.hours_type
        %td= work_unit.hours              