config/routes.rb
AssetTrackerTutorial::Application.routes.draw do
  root :to => "dashboard/base#index"

  devise_for :users, :path => '/', :path_names => { :sign_in => 'login', :sign_out => 'logout' }

  post "/data_vaults/:id", :to => "data_vaults#update"
  resources :data_vaults, :only => [:show]

  namespace :admin do
    resources :invoices
    resources :payroll
    get :locked_users, :controller => :users, :action => :locked_users
    resources :users do
      member do
        get :projects
        post :projects
      end
    end
    resources :projects
    resources :unentered_time_report
    resources :weekly_time_report
    resource :site_settings
  end
  get '/admin', :controller => "admin/base", :action => "index"
  get '/admin/reports', :controller => "admin/base", :action => "reports"

  namespace :client_login do
    root :to => "clients#index"
    resources :reports, :only => [:index] do
      collection do
        match :work_units
      end
    end
    resources :clients do
      resources :contacts
    end
    resources :projects, :tickets, :work_units
  end

  match '/client/:id' => 'clients#show'
  get :inactive_clients, :controller => :clients, :action => :inactive_clients
  get :suspended_clients, :controller => :clients, :action => :suspended_clients
  resources :clients do
    resources :comments
    resources :contacts
    get :show_complete, :controller => :clients, :action => :show_complete
  end

  resources :projects, :except => [:index, :destroy] do
    resources :comments
    get "show_complete", :controller => :projects, :action => "show_complete"
  end

  resources :tickets, :except => [:index, :destroy] do
    post 'advance_state', :controller => :tickets, :action => :advance_state
    post 'reverse_state', :controller => :tickets, :action => :reverse_state
    get 'ticket_detail', :controller => :tickets, :action => :ticket_detail
    put 'toggle_complete', :controller => :tickets, :action => :toggle_complete
    resources :comments
    resources :work_units
  end

  resources :work_units, :except => [:destroy, :create] do
    collection do 
      post :create_in_ticket
      post :create_in_dashboard
    end

    resources :comments
  end

  resources :users do
    member do
      put :change_password
      get :historical_time
    end
  end

  resources :comments

  resources :file_attachments

  namespace :dashboard do
    get :json_index, :controller => "base", :action => :json_index
    resources :base do
    end
  end

  get '/dashboard', :controller => "dashboard/base", :action => :index
  get '/dashboard/calendar', :controller => "dashboard/base", :action => "calendar"
  get '/dashboard/client', :controller => "dashboard/base", :action => "client"
  get '/dashboard/project', :controller => "dashboard/base", :action => "project"
  get '/dashboard/recent_work', :controller => "dashboard/base", :action => "recent_work"
  get '/dashboard/update_calendar', :controller => "dashboard/base", :action => "update_calendar"
  post '/file_attachments/mark_as_invalid', :controller => "file_attachments", :action => "mark_as_invalid"

  namespace :api do
    namespace :v1 do
      resources :tokens, :only => [:create, :destroy]
      resources :clients, :only => [:index]
      resources :projects, :only => [:index, :create]
      resources :tickets, :only => [:index, :show, :create]
      resources :work_units, :only => [:index, :create]
    end
  end
end

app/models/project.rb
class Project < ActiveRecord::Base
  include GuidReferenced
  acts_as_commentable
  acts_as_authorization_object
  acts_as_taggable

  github_concern :repo => :git_repo_name

  belongs_to :client
  has_many :tickets
  has_many :comments, :as => :commentable
  has_many :file_attachments
  has_one :data_vault, :as => :data_vaultable

  validates_presence_of :name
  validates_presence_of :client_id
  validates_uniqueness_of :name, :scope => :client_id

  after_create :create_data_vault

  scope :sort_by_name, order('name ASC')
  scope :for_client,    lambda {|client|    where :client_id => client.id }
  scope :for_client_id, lambda {|client_id| where :client_id => client_id }
  scope :incomplete, where(:completed => false)
  scope :complete, where(:completed => true)
  scope :with_git_repos, where(arel_table[:git_repo_url].not_eq(nil))

  scope :for_user, lambda{|user|
    joins("INNER JOIN roles r ON r.authorizable_type='#{model_name}' AND r.authorizable_id=projects.id").joins("INNER JOIN roles_users ru ON ru.role_id = r.id").joins("INNER JOIN users u ON ru.user_id = u.id").where("ru.user_id = #{user.id}")
  }

  scope :for_user_and_role, lambda{|user, role|
    joins("INNER JOIN roles r ON r.authorizable_type='#{model_name}' AND r.authorizable_id=projects.id").joins("INNER JOIN roles_users ru ON ru.role_id = r.id").joins("INNER JOIN users u ON ru.user_id = u.id").where("ru.user_id = #{user.id} AND r.name = '#{role}'")
  }

  def uninvoiced_hours
    WorkUnit.for_project(self).not_invoiced.sum(:effective_hours)
  end

  def hours
    WorkUnit.for_project(self).sum(:effective_hours)
  end

  def hours_this_month
    WorkUnit.for_project(self).scheduled_between(Time.zone.now.beginning_of_month, Time.zone.now.end_of_month).sum(:effective_hours)
  end

  def hours_this_week
    WorkUnit.for_project(self).scheduled_between(Time.zone.now.beginning_of_week, Time.zone.now.end_of_week).sum(:effective_hours)
  end

  def work_units
    WorkUnit.for_project(self)
  end

  def to_s
    if new_record?
      I18n.t(:new_project)
    else
      name
    end
  end

  def allows_access?(user)
    accepts_roles_by?(user) || user.admin?
  end

  def files_and_comments
    [comments, file_attachments].flatten.sort_by {|x| x.created_at}
  end

  private
  def create_data_vault
    self.data_vault = DataVault.create(:data_vaultable => self)
  end
end

app/controllers/api/v1/projects_controller.rb
class Api::V1::ProjectsController < Api::V1::BaseController
  before_filter :load_client_from_client_initials, :only => [:index]

  def index
    @bucket = Project.sort_by_name
    @bucket = @bucket.for_client_id(params[:client_id]) unless params[:client_id].blank?
    @bucket = @bucket.where(:git_repo_url => params[:git_repo_url]) unless params[:git_repo_url].blank?
    unless admin?
      @bucket = @bucket.for_user(current_user)
    end
    render :json => @bucket.all
  end

  def create
    @project = Project.new(params[:project])
    if @project.save
      render :json => {:success => true, :id => @project.id} and return
    else
      render :json => {:success => false, :errors => @project.errors.full_messages.to_sentence} and return
    end
  end

  private
  def load_client_from_client_initials
    params[:client_id] = Client.where(:initials => params[:client_initials]).first.id unless params[:client_initials].blank?
  end
end

app/controllers/client_login/projects_controller.rb
class ClientLogin::ProjectsController < ClientLogin::BaseController
  include ControllerMixins::Authorization

  before_filter :load_project, :only => [:show]
  before_filter :load_file_attachments, :only => [:show]

  authorize_owners_with_client_show(:project)

  # GET /projects/:id
  def show
    @tickets = Ticket.for_project(@project).sort_by_name
    # FIXME - not showing correct group of work_units
    @work_units = Project.find(params[:id]).work_units
  end

  private
  def load_project
    @project = Project.find(params[:id])
  end

  def load_file_attachments
    @file_attachments = @project.file_attachments
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  include ControllerMixins::Authorization

  before_filter :load_new_project, :only => [:new, :create]
  before_filter :load_project, :only => [:show, :edit, :update]
  before_filter :load_file_attachments, :only => [:show, :new, :create]
  before_filter :handle_tags

  authorize_owners_with_client_show(:project)

  # GET /projects/new
  def new
  end

  # POST /projects
  def create
    if @project.save
      flash[:notice] = t(:project_created_successfully)
      redirect_to @project
    else
      flash.now[:error] = t(:project_created_unsuccessfully)
      render :action => 'new'
    end
  end

  # GET /projects/:id
  def show
    @bucket = Ticket.for_project(@project).sort_by_name

    @incomplete_tickets = @bucket.incomplete
    @complete_tickets = @bucket.complete
    @work_units = Project.find(params[:id]).work_units
  end

  # GET /projects/:id/edit
  def edit
  end

  # PUT /projects/:id
  def update
    if params[:project]["completed"] == "1"
      @project.update_attribute(:completed, true)
    else
      @project.update_attribute(:completed, false)
    end

    @project.update_attributes(params[:project])
    if @project.save
      flash[:notice] = t(:project_updated_successfully)
      redirect_to [@project]
    else
      flash.now[:error] = t(:project_updated_unsuccessfully)
      render :action => 'edit'
    end
  end

  private

    def load_new_project
      @project = Project.new(params[:project])
      @project.client = Client.find(params[:client])
    end

    def load_project
      @project = Project.find(params[:id])
    end

    def load_file_attachments
      @file_attachments = @project.file_attachments
    end

    def handle_tags
      params[:project]['tag_list'] = get_tag_list_for(params[:tags]) if params[:tags]
    end

end

app/helpers/admin/projects_helper.rb
module Admin::ProjectsHelper
end

app/views/projects/_breadcrumbs.html.haml
%ul.breadcrumb
  %li
    %li= link_to "#{t(:client)}: #{@project.client}" , client_path(@project.client)
    %span.divider /
  %li= "#{t(:project)}: #{@project}"

app/views/projects/_form.html.haml
= form_for(@project, :html => { :class => 'form-horizontal' }) do |f|
  - if @project.errors.any?
    #error_explanation
      %h2
        = pluralize(@project.errors.count, "error")
        = "#{t(:prohibited_this_project_from_being_saved)}:"

      %ul
      - @project.errors.full_messages.each do |msg|
        %li= msg

  %fieldset
    %legend= legend
    .control-group
      = f.label :name, :class => 'control-label'
      .controls
        = f.text_field :name
    - if current_user.admin?
      .control-group
        = f.label :rate_a, :class => 'control-label'
        .controls
          = f.text_field :rate_a
      .control-group
        = f.label :rate_b, :class => 'control-label'
        .controls
          = f.text_field :rate_b
    .control-group
      = f.label :git_repo_name, :class => 'control-label'
      .controls
        = f.text_field :git_repo_name
    .control-group
      = f.label :git_repo_url, :class => 'control-label'
      .controls
        = f.text_field :git_repo_url
    .control-group
      = f.label :overtime_multiplier, :class => 'control-label'
      .controls
        = f.text_field :overtime_multiplier
    .control-group
      = f.label :completed, :class => 'control-label'
      .controls
        = f.check_box :completed
    .control-group
      = f.label :tags, :class => 'control-label'
      .controls
        = f.text_field :tag_list, :class => "ui-autocomplete-controls"
    = hidden_field_tag :client, @project.client.id
    .form-actions
      = f.submit :class => "add_new_button btn primary"
      = link_to t(:cancel), client_path(@project.client), :class => 'btn'

- content_for :javascripts do
  :javascript
    $(function() {
      var availableTags = #{ActsAsTaggableOn::Tag.all.map(&:name).sort};
      function split( val ) {
        return val.split( /,\s*/ );
      }
      function extractLast( term ) {
        return split( term ).pop();
      }

      $( ".ui-autocomplete-input" )
        // don't navigate away from the field on tab when selecting an item
        .bind( "keydown", function( event ) {
          if ( event.keyCode === $.ui.keyCode.TAB &&
              $( this ).data( "autocomplete" ).menu.active ) {
            event.preventDefault();
          }
        })
        .autocomplete({
          minLength: 0,
          source: function( request, response ) {
            // delegate back to autocomplete, but extract the last term
            response( $.ui.autocomplete.filter(
              availableTags, extractLast( request.term ) ) );
          },
          focus: function() {
            // prevent value inserted on focus
            return false;
          },
          select: function( event, ui ) {
            var terms = split( this.value );
            // remove the current input
            terms.pop();
            // add the selected item
            terms.push( ui.item.value );
            // add placeholder to get the comma-and-space at the end
            terms.push( "" );
            this.value = terms.join( ", " );
            return false;
          }
        });
      });

app/views/projects/_pie_chart_metrics.html.haml
%p.ticket_metrics
  = image_tag Gchart.pie(:title => "Remaining Estimated Hours vs Hours Worked Over Entire Project",
    :size => '450x230', :bar_color => "76959c,364447", :data => [100 - project_completion_metric(@project), project_completion_metric(@project)], :labels => ["Remaining Estimated", "Hours Worked"])

app/views/projects/_specify.html.haml
.yui3-u-1
  #specify_project
    #project-errors
    .yui3-u-1-2
      .ticket_field
        %label{:for => "client_id"}= "#{t(:client)}:"
        = collection_select("specify", "client_id", @clients, "id", "name", { :prompt => t(:select_a_client) })
    .yui3-u-1-2
      .ticket_field
        %label{:for => "project_id"}= "#{t(:project)}:"
        = collection_select("specify", "project_id", @projects, "id", "name", { :prompt => t(:select_a_project) })

app/views/projects/_ticket_table.html.haml
%table.tickets.table.table-striped
  %thead
    %tr
      %th  #
      %th= t(:tickets)
      %th= t(:work_units)
      %th= t(:uninvoiced_hours)
      %th= t(:total_hours)
      %th= t(:percent_complete)
      - if admin? || current_user.has_role?(:developer, @project)
        %th= t(:edit)
  %tfoot
    %tr
      %th= t(:all_tickets)
      %th &nbsp;
      %th= @project.work_units.count
      %th= @project.uninvoiced_hours
      %th= @project.hours
      %th &nbsp;
      - if admin? || current_user.has_role?(:developer, @project)
        %th &nbsp;
  %tbody
    - if tickets.any?
      - tickets.each do |ticket|
        %tr
          %td= ticket.id
          %td= link_to ticket, ticket
          %td= ticket.work_units.count
          %td= ticket.uninvoiced_hours
          %td= ticket.hours
          %td= progress_bar(ticket.percentage_complete, :color => 'blue', :rounded => true)
          - if admin? || current_user.has_role?(:developer, @project)
            %td= link_to t(:edit), edit_ticket_path(ticket), :class => 'btn'
    - else
      %tr
        %td{:colspan => 6} No Tickets to Show

app/views/projects/edit.html.haml
= render 'breadcrumbs'
= render 'form', :legend => t(:edit_project)

app/views/projects/new.html.haml
= render 'breadcrumbs'
= render 'form', :legend => t(:new_project)

app/views/projects/show.html.haml
= render 'breadcrumbs'

- if admin? || current_user.has_role?(:developer, @project)
  .btn-group
    = link_to bootstrap_icon('edit') + t(:edit_project), edit_project_path, :class => 'btn', :rel => 'edit-project'
    = link_to bootstrap_icon('plus') + t(:new_ticket), new_ticket_path(:project_id => @project), :class => 'btn'
  %br
  %br

- if current_user.admin?
  %ul
    %li= "Rate A: #{number_to_currency(@project.rate_a)}"
    %li= "Rate B: #{number_to_currency(@project.rate_b)}"

%ul.nav.nav-tabs{"data-tabs" => "tabs"}
  -if !@project.xrono_notes.nil?
    %li.active= link_to "Project Notes", "#project_notes"
  -if !@project.release_notes.nil?
    %li{:class => "#{@project.xrono_notes.nil? ? "active" : ""}"}= link_to "Release Notes", "#release_notes"
  %li{:class => "#{@project.xrono_notes.nil? && @project.release_notes.nil? ? "active" : ""}"}= link_to "Incomplete Tickets", "#incomplete_tickets"
  %li= link_to "Complete Tickets", "#complete_tickets"
  %li= link_to "Data Vault", "#data_vault"
  %li= link_to "Comments and Files", "#comments"

.tab-content
  -if !@project.xrono_notes.nil?
    #project_notes.tab-pane.active
      :kramdown
        #{@project.xrono_notes}
  -if !@project.release_notes.nil?
    #release_notes.tab-pane{:class => "#{@project.xrono_notes.nil? ? "active" : ""}"}
      :kramdown
        #{@project.release_notes}
  #incomplete_tickets.tab-pane{:class => "#{@project.xrono_notes.nil? && @project.release_notes.nil? ? "active" : ""}"}
    - if project_completion_metric(@project) > 0
      = progress_bar(project_completion_metric(@project), :color => 'blue', :rounded => true)
    = render "ticket_table", :tickets => @incomplete_tickets
  #complete_tickets.tab-pane
    - if project_completion_metric(@project) > 0
      = progress_bar(project_completion_metric(@project), :color => 'blue', :rounded => true)
    = render "ticket_table", :tickets => @complete_tickets
  #data_vault.tab-pane
    = render "shared/data_vault", :data_vault => @project.data_vault
  #comments.tab-pane
    - unless current_user.client
      = render "shared/files_and_comments", :items => @project.files_and_comments.reverse, :id => 'project'

  - content_for :javascripts do
    = javascript_include_tag "ticket_board"
    = javascript_include_tag "bootstrap-tabs"
    :javascript
      $(function() {
        $('.tabs').tabs();
      });