config/routes.rb
AssetTrackerTutorial::Application.routes.draw do
  root :to => "dashboard/base#index"

  devise_for :users, :path => '/', :path_names => { :sign_in => 'login', :sign_out => 'logout' }

  post "/data_vaults/:id", :to => "data_vaults#update"
  resources :data_vaults, :only => [:show]

  namespace :admin do
    resources :invoices
    resources :payroll
    get :locked_users, :controller => :users, :action => :locked_users
    resources :users do
      member do
        get :projects
        post :projects
      end
    end
    resources :projects
    resources :unentered_time_report
    resources :weekly_time_report
    resource :site_settings
  end
  get '/admin', :controller => "admin/base", :action => "index"
  get '/admin/reports', :controller => "admin/base", :action => "reports"

  namespace :client_login do
    root :to => "clients#index"
    resources :reports, :only => [:index] do
      collection do
        match :work_units
      end
    end
    resources :clients do
      resources :contacts
    end
    resources :projects, :tickets, :work_units
  end

  match '/client/:id' => 'clients#show'
  get :inactive_clients, :controller => :clients, :action => :inactive_clients
  get :suspended_clients, :controller => :clients, :action => :suspended_clients
  resources :clients do
    resources :comments
    resources :contacts
    get :show_complete, :controller => :clients, :action => :show_complete
  end

  resources :projects, :except => [:index, :destroy] do
    resources :comments
    get "show_complete", :controller => :projects, :action => "show_complete"
  end

  resources :tickets, :except => [:index, :destroy] do
    post 'advance_state', :controller => :tickets, :action => :advance_state
    post 'reverse_state', :controller => :tickets, :action => :reverse_state
    get 'ticket_detail', :controller => :tickets, :action => :ticket_detail
    put 'toggle_complete', :controller => :tickets, :action => :toggle_complete
    resources :comments
    resources :work_units
  end

  resources :work_units, :except => [:destroy, :create] do
    collection do 
      post :create_in_ticket
      post :create_in_dashboard
    end

    resources :comments
  end

  resources :users do
    member do
      put :change_password
      get :historical_time
    end
  end

  resources :comments

  resources :file_attachments

  namespace :dashboard do
    get :json_index, :controller => "base", :action => :json_index
    resources :base do
    end
  end

  get '/dashboard', :controller => "dashboard/base", :action => :index
  get '/dashboard/calendar', :controller => "dashboard/base", :action => "calendar"
  get '/dashboard/client', :controller => "dashboard/base", :action => "client"
  get '/dashboard/project', :controller => "dashboard/base", :action => "project"
  get '/dashboard/recent_work', :controller => "dashboard/base", :action => "recent_work"
  get '/dashboard/update_calendar', :controller => "dashboard/base", :action => "update_calendar"
  post '/file_attachments/mark_as_invalid', :controller => "file_attachments", :action => "mark_as_invalid"

  namespace :api do
    namespace :v1 do
      resources :tokens, :only => [:create, :destroy]
      resources :clients, :only => [:index]
      resources :projects, :only => [:index, :create]
      resources :tickets, :only => [:index, :show, :create]
      resources :work_units, :only => [:index, :create]
    end
  end
end

app/models/contact.rb
class Contact < ActiveRecord::Base
  belongs_to :client

  validates_presence_of :first_name
  validates_presence_of :last_name
  validates_presence_of :email_address

  scope :for_client, lambda{ |client| where(:client_id => client.id)}
  scope :receives_email, where(:receives_email => true)
end

app/controllers/client_login/base_controller.rb
class ClientLogin::BaseController < ApplicationController
  skip_before_filter :redirect_clients
end

app/controllers/client_login/clients_controller.rb
class ClientLogin::ClientsController < ClientLogin::BaseController
  before_filter :load_client, :only => [:show]

  access_control do
    allow :admin

    action :index do
      allow :client
    end

    action :show do
      allow :client, :if => :user_is_authorized
    end
  end

public
  def index
    bucket = Client.order("name")
    if admin?
      bucket = bucket.all
    else
      bucket = bucket.for_user(current_user)
    end
    @clients = bucket.all
    redirect_to client_login_client_path(@clients.first) if @clients.count == 1
  end

  def show
    bucket = Project.sort_by_name.for_client(@client)
    bucket = bucket.for_user(current_user) unless admin?
    @projects = bucket.all
  end

private
  def user_is_authorized
    @client.allows_access? current_user
  end

  def load_client
    @client = Client.find(params[:id])
  end
end

app/controllers/client_login/contacts_controller.rb
class ClientLogin::ContactsController < ClientLogin::BaseController
  include ControllerMixins::Contacts

  before_filter :load_client
  before_filter :load_contact, :only => [:show, :edit, :update, :destroy]

  access_control do
    allow :client, :to => [:new, :create, :edit, :update, :show, :index], :if => :client_is_current_client?
  end

protected
  def load_client
    @client = Client.find(params[:client_id])
  end

  def load_contact
    @contact = Contact.find(params[:id])
  end


public
  def index
    @contacts = @client.contacts.all
  end

  def show
  end

  def new
    @contact = Contact.new(params[:contact])
  end

  def create
    create!(:client_login_client_contact_path)
  end

  def update
    update!(:client_login_client_contact_path)
  end

  def edit
  end

  def destroy
    destroy!(:client_login_client_contacts_path)
  end

private
  def client_is_current_client?
    Client.for_user(current_user).include?(@client)
  end

end

app/controllers/client_login/projects_controller.rb
class ClientLogin::ProjectsController < ClientLogin::BaseController
  include ControllerMixins::Authorization

  before_filter :load_project, :only => [:show]
  before_filter :load_file_attachments, :only => [:show]

  authorize_owners_with_client_show(:project)

  # GET /projects/:id
  def show
    @tickets = Ticket.for_project(@project).sort_by_name
    # FIXME - not showing correct group of work_units
    @work_units = Project.find(params[:id]).work_units
  end

  private
  def load_project
    @project = Project.find(params[:id])
  end

  def load_file_attachments
    @file_attachments = @project.file_attachments
  end
end

app/controllers/client_login/reports_controller.rb
class ClientLogin::ReportsController < ClientLogin::BaseController
  before_filter :load_projects, :only => [:work_units]
  def index
  end

  def work_units
    params[:start_date_hidden] ||= Date.current.beginning_of_month.to_s
    params[:end_date_hidden] ||= Date.current.end_of_month.to_s
    start_date = Time.zone.parse(params[:start_date_hidden]).beginning_of_day
    end_date = Time.zone.parse(params[:end_date_hidden]).end_of_day
    if params[:project_id].nil?
      project = Project.for_user(current_user).first
    else
      project = Project.for_user(current_user).find params[:project_id]
    end
    @work_units = WorkUnit.order("scheduled_at desc").for_project(project).scheduled_between(start_date,end_date)
  end

  private
  def load_projects
    @projects = Project.for_user(current_user)
  end
end

app/controllers/client_login/tickets_controller.rb
class ClientLogin::TicketsController < ClientLogin::BaseController
  include ControllerMixins::Tickets

  before_filter :load_new_ticket, :only => [:new, :create]
  before_filter :load_ticket, :only => [:show, :edit, :update, :advance_state, :reverse_state, :ticket_detail]
  before_filter :load_project

  access_control do
    allow :admin
    allow :developer, :of => :project
    allow :client, :of => :project, :to => [:show, :new, :create]
  end

  # GET /tickets/new
  def new
  end

  # POST /tickets
  def create
    @ticket.estimated_hours = 0.0
    create!(:client_login_ticket_path) # In ControllerMixins::Tickets module
  end

  # GET /tickets/:id
  def show
    @work_units = WorkUnit.for_ticket(@ticket).sort_by_scheduled_at
    unless @ticket.estimated_hours
      flash.now[:notice] = "NOTE: The estimated amount of time to complete this ticket has not been entered."
    end

    if @ticket.percentage_complete.to_i > 100
      flash.now[:notice] = "WARNING: Ticket has exceeded the estimated amount of time to be completed."
    end
  end

  private
  # Acl9's access control block looks for @project in order to use "allow <role> :of => :project"
  def load_project
    @project = @ticket.project
  end
end

app/controllers/client_login/work_units_controller.rb
class ClientLogin::WorkUnitsController < ClientLogin::BaseController
  include ControllerMixins::WorkUnits
  include ControllerMixins::Authorization

  authorize_owners_with_client_show(:project)

  # GET /work_units/:id
  def show
    @work_unit = WorkUnit.find params[:id]
  end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  include ControllerMixins::Contacts

  before_filter :load_client
  before_filter :load_contact, :only => [:show, :edit, :update, :destroy]
  before_filter :require_admin, :only => [:destroy]

  access_control do
    allow :admin
    allow :developer, :if => :current_user_has_client
    allow :client, :to => [:new, :create, :edit, :update, :destroy, :show, :index], :if => :current_user_has_client
  end


  protected
  def load_client
    @client = Client.find(params[:client_id])
  end

  def load_contact
    @contact = Contact.find(params[:id])
  end


  public
  def index
    @contacts = @client.contacts.all
  end

  def show
  end

  def new
    @contact = Contact.new(params[:contact])
  end

  def create
    create!(:client_contact_path)
  end

  def update
    update!(:client_contact_path)
  end

  def edit
  end

  def destroy
    destroy!(:client_contacts_path)
  end

private
  def current_user_has_client
    Client.for_user(current_user).include?(@client)
  end

end

app/helpers/client_login/reports_helper.rb
module ClientLogin::ReportsHelper
end

app/views/client_login/contacts/_form.html.haml
- if @contact.errors.any?
  #error_explanation
    %h2
      = pluralize(@contact.errors.count, "error")
      prohibited this contact from being saved:
    %ul
    - @contact.errors.full_messages.each do |msg|
      %li= msg
%fieldset
  .clearfix
    = f.label :first_name
    .input
      = f.text_field :first_name
  .clearfix
    = f.label :last_name
    .input
      = f.text_field :last_name
  .clearfix
    = f.label :email_address
    .input
      = f.text_field :email_address
  .clearfix
    = f.label :phone_number
    .input
      = f.text_field :phone_number
    .clearfix
      .input
        %ul.inputs-list
          %li
            %label
              = f.check_box :receives_email
              %span Receives Email
  .actions
    = f.submit :class => "add_new_button btn primary"

app/views/client_login/contacts/edit.html.haml
.module
  %h2="Edit #{@contact.first_name} #{@contact.last_name}"
  = form_for [:client_login, @contact], :url => client_login_client_contact_path do |f| 
    = render 'form', :f => f

app/views/client_login/contacts/index.html.haml
.yui3-g
  .yui3-u-1
    %h2= "#{@client} #{t(:contacts)}:"
.yui3-g
  .yui3-u-1
    .gradient_border_wrap
      .gradient_border_content
        %table.clients
          %thead
            %tr
              %th= t(:first_name)
              %th= t(:last_name)
              %th= t(:email_address)
              %th= t(:phone_number)
              %th= t(:receives_email)
              %th= t(:edit)
          %tbody
            - @contacts.each do |contact|
              %tr
                %td= link_to contact.first_name, client_login_client_contact_path(contact.client, contact)
                %td= contact.last_name
                %td= contact.email_address
                %td= contact.phone_number
                -if contact.receives_email == true
                  %td= t(:affirmative)
                - else
                  %td= t(:negative)
                %td= link_to t(:edit), edit_client_login_client_contact_path(contact.client, contact), :class => 'btn'

        = link_to t(:new_contact), new_client_login_client_contact_path, :class => "add_new_button btn primary"

app/views/client_login/contacts/new.html.haml
.module
  %h2= t(:new_contact)

  = form_for [:client_login, @contact], :url => client_login_client_contacts_path do |f| 
    = render 'form', :f => f

app/views/client_login/contacts/show.html.haml
%h2= "#{t(:contact)}: #{@contact.first_name} #{@contact.last_name}"

%ul.nav.nav-pills
  %li= link_to t(:all_contacts), client_login_client_contacts_path
  %li= link_to t(:edit_contact), edit_client_login_client_contact_path(@client)
  %li= button_to t(:delete_contact), client_login_client_contact_path(@contact.client, @contact), :method => :delete, :confirm => t(:are_you_sure), :class => 'btn'

#client
  %table.table.table-striped
    %thead
      %tr
        %th= t(:first_name)
        %th= t(:last_name)
        %th= t(:email_address)
        %th= t(:phone_number)
        %th= t(:receives_email)
    %tbody
      %tr
        %td= @contact.first_name
        %td= @contact.last_name
        %td= @contact.email_address
        %td= @contact.phone_number
        - if @contact.receives_email == true
          %td= t(:affirmative)
        - else
          %td= t(:negative)